### ISSUE TITLE
Нуллабилити

### ISSUE THREAD

**Issue by fcknvmbr** [legaluser/FirstApp#1]
https://github.com/legaluser/FirstApp/blob/41bd46e27b19482051679ce4d61433d5d67764e8/app/src/main/java/ru/startandroid/myapplication/ChangeName.java#L12

Почитай про @Nullable и @Notnull аннотации, пишешь их и потом android studio сама подсказывать начинает, где поля надо проверить на null, чтобы не было NPE.

**Comment by legaluser** [comment]
поправил
