### ISSUE TITLE
Осмысленно подходить к названию классов и переменных

### ISSUE THREAD

**Issue by PaulProject** [legaluser/FirstApp#11]
Например, в RepoAdapter.java есть holder с названием ViewHolder, есть смысл назвать его как RepositoryHolder. Внутри holder есть поле name и URL, хотя по факту это View, следовательно мне не понятно не заглядывая в код, что это view. Мой совет называть ImageView как img<YourName>, а TextView как txt<YourName>. Необходимо пройти по всему приложению и исправить

**Comment by legaluser** [comment]
поправил
