### ISSUE TITLE
Вытащить работу с Activity в отдельное View

### ISSUE THREAD

**Issue by PaulProject** [legaluser/FirstApp#16]
Например в одном из презентеров есть код                         myRecyclerView.getAdapter().notifyDataSetChanged(); презентер ничего не должен знать об твоем RecyclerView, он должен взаимодействовать с интерфейсом, а интерфейс уже должен реализовывать myRecyclerView.getAdapter().notifyDataSetChanged()

**Comment by legaluser** [comment]
Поправил
