### ISSUE TITLE
Доступ к полям

### ISSUE THREAD

**Issue by fcknvmbr** [legaluser/FirstApp#2]
https://github.com/legaluser/FirstApp/blob/41bd46e27b19482051679ce4d61433d5d67764e8/app/src/main/java/ru/startandroid/myapplication/ListUsersFragment.java#L49

Лучше вынести всякие глобальные вещи, типа бокового меню, тулбара etc в переменные уровня полей класса, чтобы в дальнейшем их можно было использовать вне onCreate() метода

**Comment by legaluser** [comment]
поправил
