### ISSUE TITLE
Дублирование кода

### ISSUE THREAD

**Issue by fcknvmbr** [legaluser/FirstApp#3]
https://github.com/legaluser/FirstApp/blob/41bd46e27b19482051679ce4d61433d5d67764e8/app/src/main/java/ru/startandroid/myapplication/MainActivity.java#L171

Можно вынести установку HTML-текста в TextView в отдельную функцию в Utils.java, куда передовать нужный TextView и HTML-разметку. Что-то вроде 
`void Utils.setTextFromHtml(TextView textView, String htmlString)`

**Comment by legaluser** [comment]
исправил
