### ISSUE TITLE
Обработка действий на клики элементов списка

### ISSUE THREAD

**Issue by fcknvmbr** [legaluser/FirstApp#4]
https://github.com/legaluser/FirstApp/blob/41bd46e27b19482051679ce4d61433d5d67764e8/app/src/main/java/ru/startandroid/myapplication/MyAdapter.java#L38

Таки штуки лучше делать вот так: https://stackoverflow.com/questions/15444375/how-to-create-interface-between-fragment-and-adapter

1. Улучшит чистоту кода
2. Стартовать фрагмент не зона ответственности адаптера
3. При множестве различных действий адаптер будет разрастаться, если делать таким образом

**Comment by legaluser** [comment]
Переделал
