### ISSUE TITLE
Private и Public модификаторы

### ISSUE THREAD

**Issue by fcknvmbr** [legaluser/FirstApp#6]
https://github.com/legaluser/FirstApp/blob/41bd46e27b19482051679ce4d61433d5d67764e8/app/src/main/java/ru/startandroid/myapplication/RepoInfo.java#L14

При большом числе полей, как здесь, очень много get() и set() методов. А нужны ли они нам вообще?

https://www.youtube.com/watch?v=lfdAwl3-X_c

**Comment by legaluser** [comment]
исправил
