### ISSUE TITLE
Разделение приложения на логические пакеты

### ISSUE THREAD

**Issue by PaulProject** [legaluser/FirstApp#7]
Приложение тяжело читается, если не делить его на логические пакеты. Есть несколько способов разделить его, например все адаптеры поместить в папку adapters. Я рекомендую делить на пакеты по функциональному типу, например создать пакет user, в нем создать пакет list, в нем расположить все что касается списка пользователей, в пакете user поместить то что касается отдельного пользователя

**Comment by legaluser** [comment]
сделал
